key_name = "turn-key" 
public_key_path = "/home/ec2-user/turn-key.pub" 
ami = "ami-0150ccaf51ab55a51"
s3_bucket_name = "my-turn-project-bucket-unique-12345"
subnet_id_1 = "subnet-xxxxxxx"
subnet_id_2 = "subnet-yyyyyyy"
